### ISSUE TITLE
Energy meter slowing power throughput down to a crawl

### ISSUE THREAD

**Issue by djoveryde** [RLNT/minecraft_energymeter#20]
### Version

energymeter-1.18.1-3.1.1

### Describe the bug!

I am currently running on All the Mods 7 and have placed an energy meter between Energy Batteries from Integrated Dynamics and numerous powered items connected using Energy Pipez from the Pipez mod.
If I put a powered item on the cable just before the Energy meter it powers it to 1 million RF instantly.
However if I place the same item after the Energy meter, its slowly charging up (about 30 rf /t).
I have tried this bypassing the energy meter (with everything plugged in still) and it charges instantly so at this stage I am assuming that the energy meter is somehow capping the throughput.

### Additional Context

Yes

### Did the issue happen in singleplayer or on a server?

Server

**Comment by rlnt** [comment]
This is not possible. The Energy Meter redirects all incoming energy calls directly to its output sides.
It is not limiting any energy at any point. The only things that limit energy throughput are the connected objects.
If you attach something to the output which only accepts 1kFE/t (as an example), the throughput will be 1kFE/t because the output can't accept more.

The only reason for this could be some mess with Pipez. Pipez is not implemented like other cable mods and requires a workaround. This workaround still shouldn't cause this behavior but like in previous versions, they probably forget to invalidate their capabilities.

Is there a video you could make to demonstrate the issue?

**Comment by djoveryde** [comment]
I can certainly try, in regards to pipez I tried using the infinite upgrade which "apparently" allows 2147 million rf/t to go through the pipe which is heavily more than enough but it doesn't seem to update. 
Is it because i'm having to add a card in to upgrade the cable that the meter or pipe doesn't update this change?
I also placed the output cable in the back of the meter.

**Comment by rlnt** [comment]
I am having a hard time understanding your setup to replicate the issue so a video would be much appreciated.

And it depends if Pipez is sending a block update when inserting the upgrade.
This might be a Pipez issue. I will take a look at the video and then try to reproduce this and then submit the necessary changes to Pipez if needed.
You can also try it with some other cable mod besides Pipez just to make sure.

**Comment by djoveryde** [comment]
It would be pretty difficult to replicate the issue as you'd likely need a lot of power draining items in order to duplicate the issue. I would only be showing you a fraction of the setup. 
One side note though is that I keep having to re-link the pipez output to the energy meter after a few minutes and even at times the meter reads 0 but shows connected. Logging out and back in again shows that the pipez output is no longer set to output so pondering if pipez is the issue.

At the moment I have an [integrateddynamics energy battery] -----[Energy Pipez (infinity pipe upgrade)]-----> [Energy Meter] ----[Energy Pipe (Ininity pipe Upgrade)]-----> [Charging station from Charging Gadgets] + [many other powered items] (using over 2.2 kRF/t). The charging gadget is what i'm currently use to test the power. Removing the energy meter and connecting together gives an instant charge rather than a slow tick.

**Comment by djoveryde** [comment]
I have also just noticed that server is spamming me with an crash report. I've grabbed it and pasted it here. Hope this helps

https://pastebin.com/v6BgLfKg

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/v6BgLfKg">pipez/Energy Meter crash? - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rlnt** [comment]
> I have also just noticed that server is spamming me with an crash report. I've grabbed it and pasted it here. Hope this helps

That looks like you've built a loop. And the output of the Energy Meter is feeding into the input again.
I am waiting for the video otherwise I can't do anything.

**Comment by djoveryde** [comment]
That was when trying to tell the end of the energy pipe to re-connect to the back of the energy meter, it just spammed console. Stone between the cables to prevent creating a loop. 
I can't easily produce a video so don't worry about it. I'll just close the issue.

**Comment by rlnt** [comment]
I mean I would like to fix that but I can't if I am not able to reproduce it.
If you have found a solution, that's fine.

**Comment by djoveryde** [comment]
I unfortunately didn't find a solution, the issue is showing how to replicate and at the same time getting it to replicate. For the lack of power issue you'd need to pushing a good amount of power to power devices (2.3kRF/t).
For the sake of having stable power and the output from integrated dynamics energy battery and energy pipe from Pipez not constantly bugging out i've had to bypass the meter all together.
