### ISSUE TITLE
[1.16.5] SMP server side startup crash

### ISSUE THREAD

**Issue by ptk2003** [RLNT/minecraft_energymeter#3]
energymeter-1.16.5-1.1.0.jar
forge-1.16.5-36.2.2.jar

Failure message: Energy Meter (energymeter) encountered an error during the common_setup event phase java.lang.ExceptionInInitializerError: null
	Mod Version: 1.1.0
	Mod Issue URL: https://github.com/RLNT/minecraft_energymeter/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER

[crash-2021-10-06_11.03.36-fml.txt](https://github.com/RLNT/minecraft_energymeter/files/7291957/crash-2021-10-06_11.03.36-fml.txt)

**Comment by rlnt** [comment]
Thanks for the report, the update will be uploaded shortly!
