### ISSUE TITLE
New Types of Meter

### ISSUE THREAD

**Issue by DevDyna** [RLNT/minecraft_energymeter#34]
### Describe the feature/addition!

*(i know that could be a bit out of context but maybe could be good)*
Many new types of *meters* based on other types of *powers* so players can use it more frequently on small circuits and endgame farms
List of potential *meters*:
- Item
- Fluid
- Redstone (?) / MSPT
- Gas (Mekanism)
- Source (Ars Nouveau)
- Mana (Botania)
- Zap (FTBIC)

### Why would like to see this feature/addition?

Energy meter mod still a good mod but due the "low content" it can be completly override like using something like mekanism induction matrix losing the "main scope"
So more meters could make it a unique mod with unique features that other mods still missing

**Comment by rlnt** [comment]
I have some more features planned when I find the time but meters for non-energy types are out of scope and not planned. I will take a look at Zaps tho.
