### ISSUE TITLE
Mining the energy meter block does not drop item

### ISSUE THREAD

**Issue by Cynix32** [RLNT/minecraft_energymeter#4]
## Bug Description

Mining the energy meter block does not drop the corresponding item.

## Expected Behavior

The energy meter item should drop when mined

## Current Behavior

nothing happens, no drops.

## Possible Solution

I will PR a fix that makes a loot table for the block.

## Reproduction

1. Craft energy meter
2. mine energy meter with pickaxe of choice
3. literally nothing happens or drops

## Versions

MC 1.16.5
Forge 36.2.8
GraalVM Community Java 8
energymeter-1.16.5-1.2.0.jar
Windows 10 64 bit

**Comment by rlnt** [comment]
Whoops, right.
I actually thought about saving the I/O configuration to the block when dropping it and when I decided to not do that, I completely forgot to add a loot table.
Thanks for the report.

**Comment by rlnt** [comment]
When the GitHub workflow is done, it will be automatically published on CurseForge and should be available shortly after.
Thanks again.
